---
- name: play1
  hosts: localhostgrp
  tasks:
    - name: play1 and task1
      ansible.builtin.debug:
        msg: This message is from play1-task1
    - name: play1 and task2
      ansible.builtin.debug:
        msg: This message is from play1-task2
- name: play2
  hosts: localhost
  tasks:
    - name: play2 and task1
      ansible.builtin.debug:
        msg: This message is from play2-task1
    - name: play2 and task2
      ansible.builtin.debug:
        msg: This message is from play2-task2