---
- name: play-vars at play and task level
  hosts: localhostgrp
  vars:
    course: "devops"
    faculty: "suresh"
    duration: "100hrs"
  tasks:
  - name: task vars at play and task level
    vars:
      course: "devops with aws"
    ansible.builtin.debug:
      msg: "The training of {{course}} course will take {{duration}} by {{faculty}}"